theme: jekyll-theme-minimal
title: A Digital Life
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: kerner1000
url: https://kerner1000.github.io