theme: jekyll-theme-minimal
title: A Digital Life
description: My Notebook
permalink: /:year/:month/:day/:title
author: kerner1000
url: https://kerner1000.github.io
owner:
  avatar: kerner1000-avatar.png
  email: alexkerner1000@gmail.com