remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: A Digital Life
description: My Notebook
permalink: /:year/:month/:day/:title
author: kerner1000
url: https://kerner1000.github.io
owner:
  avatar: kerner1000-avatar.png
  email: alexkerner1000@gmail.com